---
# Install openmanage collection by running -> `ansible-galaxy collection install dellemc.openmanage` before running this playbook
- name: Apply BIOS settings for Dell Hardware via iDRAC
  hosts: vpac-rhel-200
  gather_facts: no
  vars_files:
  - vars/secrets.yml
  tasks:
  - name: Set BIOS attributes
    dellemc.openmanage.idrac_bios:
      idrac_ip: "{{ idrac_ip }}"
      idrac_user: "{{ idrac_user }}"
      idrac_password: "{{ idrac_password }}"
      validate_certs: no
      attributes:
        ProcTurboMode: "Disabled"     # Disable Turbo Boost
        LogicalProc: "Disabled"       # Disable Hyper-Threading
        SysProfile: "Performance"     # Set System Profile to Performance mode
        ProcCStates: "Disabled"       # Disable CPU Power Management
        ProcPwrPerf: "MaximumPerformance"  # Set CPU Performance to Max
        MemFrequency: "MaxPerformance"    # Optimize Memory Speed
        WorkloadProfile: "NotConfigured"  # Ensure manual control
        VirtualizationTechnology: "Enabled"  # Enable Virtualization
    register: bios_result

  - name: Apply BIOS settings (Reboot Required)
    dellemc.openmanage.idrac_job:
      idrac_ip: "{{ idrac_ip }}"
      idrac_user: "{{ idrac_user }}"
      idrac_password: "{{ idrac_password }}"
      validate_certs: no
      job_id: "{{ bios_result.job_id }}"
      job_wait: true
