---
# VPac
- name: VPAC setup
  hosts: vpac-rhel-200
  gather_facts: yes
  
  vars_files:
  - vars/secrets.yml
  - vars/vpac-settings.yaml
  
  tasks:
  - name: vpac setup
    ansible.builtin.include_role:
      name: kwozyman.vpac
