---
# VPac
- name: ABB SSC600 setup
  hosts: vpac-rhel-200
  gather_facts: yes
  
  vars_files:
  - vats/vpac-settings.yaml

  tasks:
  - name: vpac setup
    ansible.builtin.include_role:
      name: kwozyman.ssc600
